### ISSUE TITLE
there is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by ArunGust** [aembke/fred.rs#10]
I got below error when calling from actix web request. Any idea  ?

thread 'actix-rt:worker:0' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', D:\RUST\CARGO\registry\src\github.com-1ecc6299db9ec823\fred-4.2.0\src\client.rs:179:5

**Comment by aembke** [comment]
Now that actix has released 4.x I'm going to close this.
