### ISSUE TITLE
How to set a key:value where value is a complex struct

### ISSUE THREAD

**Issue by oren0e** [aembke/fred.rs#112]
I want to set a key which is `String` and a value which is a struct that has all kinds of types for its fields like `Option<T>` where `T` in `String, serde_json::Value, i64, f64, bool` etc. I didn't see that in the documentation. How can I do that?

**Comment by aembke** [comment]
Does this work for you? https://github.com/aembke/fred.rs/blob/main/examples/serde.rs#L39-L53

(To save you a click)

```rust 
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
struct Person {
  name:   String,
  age:    u8,
  phones: Vec<String>,
}

// ...

  let person = Person {
    name:   "Foo".into(),
    age:    42,
    phones: vec!["abc".into(), "123".into()],
  };

  let serialized = serde_json::to_string(&person)?;
  let _: () = client.set("person 1", serialized, None, None, false).await?;
  // deserialize as a json value
  let deserialized: Person = serde_json::from_value(client.get::<Value, _>("person 1").await?)?;
  assert_eq!(person, deserialized);
  // or as a json string
  let deserialized: Person = serde_json::from_str(&client.get::<String, _>("person 1").await?)?;
  assert_eq!(person, deserialized);
```

**Comment by AlexMikhalev** [comment]
Bump. I tried serde example, and I was expecting that similar to JSON object a few lines above `
let _: () = client.hset("wobble", value.clone()).await?;`  I could save person into hset: 
```
 let person = Person {
    name:   "Foo".into(),
    age:    42,
    phones: vec!["abc".into(), "123".into()],
  };
let _: () = client.hset("person1", person.clone()).await?;
```
but it fails with
```let _: () = client.hset("person1", person.clone()).await?;
   |                      ^^^^ the trait `From<Person>` is not implemented for `RedisMap`
```
the comment above `// json `Value` objects can also be used interchangeably with `RedisMap` type arguments.` indicates it shall be possible. Any hints on saving complex data structures into Redis?

**Comment by AlexMikhalev** [comment]
if we can maintain hash vs serialisation to string we can create Redis Search index for hash with different fields.

**Comment by aembke** [comment]
Yeah, this interface was misleading both in the documentation and underlying type conversion logic. I removed the automatic conversion logic in 7.x (starting at https://crates.io/crates/fred/7.0.0-rc.1) to avoid this, so callers will have to serialize values beforehand. The serde-json example was updated to make this clearer as well.
