### ISSUE TITLE
Is it possible to implement all traits on SubscriberClient?

### ISSUE THREAD

**Issue by mkurtak** [aembke/fred.rs#121]
If RESP3 is used (see [HELLO](https://redis.io/commands/hello)), a client can issue any commands while in the subscribed state (from https://redis.io/docs/manual/pubsub/). 

So maybe `SubscriberClient` could implement the same traits as `RedisClient` and we wouldn't need 2 clients when working with `SubscriberClient`. What do you think?

**Comment by aembke** [comment]
Thats a good idea. I'll put this in 6.1.0 (via https://github.com/aembke/fred.rs/pull/122)

**Comment by aembke** [comment]
Added in https://github.com/aembke/fred.rs/pull/117
