### ISSUE TITLE
Intermittent failure to connect with wait_for_connect on StaticPool

### ISSUE THREAD

**Issue by DnMllr** [aembke/fred.rs#14]
Hello, I have written a test using [testcontainer](https://github.com/testcontainers/testcontainers-rs) with the following code and I'm seeing an error of: `Redis Error - kind: Unknown, details: Redis connection is not initialized` every once in a while. For the most part it works fine, but sometimes that `.expect` fails at the call to `.ping`. It seemed to me that the rate of failure decreased with an increase in the size of the `StaticRedisPool` so I wonder if there's some condition under which `.wait_for_connect` returns before every client has connected?

```rust
    use testcontainers::{clients::Cli, images::redis::Redis, Docker};

    #[tokio::test]
    async fn test_condition() {
        let docker = Cli::default();
        let container = docker.run(Redis::default());

        let port = container
            .get_host_port(6379)
            .expect("should be able to get host port");

        let pool = StaticRedisPool::new(
            RedisConfig {
                server: ServerConfig::new_centralized("127.0.0.1", port),
                ..Default::default()
            },
            3,
        )
        .unwrap();

        let _ = pool.connect(None);
        pool.wait_for_connect().await.unwrap();

        pool.ping().await.expect("should be able to ping");
    }
```

Please let me know if you would benefit from any further details or I missed something.

**Comment by aembke** [comment]
Hi @DnMllr, thanks for looking into this. Some of the pooling code looks suspect so I'm guessing you're right about there being some inconsistent behavior here. I'll take a look this weekend and update here shortly. This may also be related to https://github.com/aembke/fred.rs/issues/13

**Comment by aembke** [comment]
Hi @DnMllr, I just merged some changes that should address this. The issue was in the implementation for the static pool `wait_for_connect` as you suspected. I was able to repro the issue in the tests and after these changes the issue no longer repro's for me. 

I'll wait to close this until you have a chance to check on your side though.
