### ISSUE TITLE
[Bug] Support multiple IPs result in DNS resolver 

### ISSUE THREAD

**Issue by DDtKey** [aembke/fred.rs#143]
Redis version - doesn't matter
Platform - doesn't matter
Using Docker and/or Kubernetes - no
Deployment type - cluster

**Describe the bug**
DNS might contain multiple records, but current interface of `DnsResolver` expects only single address. 

Don't think that this functionality should be part of implementation of `DnsResolver`, instead trait should be changed to return slice/vector of addresses. For example, `reqwest` crate has such [definition of the resolver](https://github.com/seanmonstar/reqwest/blob/00be85efd9683768f51f5bc75895fe8693914014/src/dns/resolve.rs#L14-L29) and [example of handling](https://github.com/seanmonstar/reqwest/blob/00be85efd9683768f51f5bc75895fe8693914014/src/async_impl/h3_client/connect.rs#L71-L85)

**To Reproduce**
1. It should be more than 1 `A or AAAA` records for domain
2. One of them doesn't work (during failover for example)

**Logs**
It's just connection errors, because dns-resolver can provide only one IP

**Comment by DDtKey** [comment]
Example where it's really helpful: Amazon MemoryDB with it's configuration endpoint

For correct failover I had to randomize IP choosing

**Comment by aembke** [comment]
This was added in 7.x (starting at https://crates.io/crates/fred/7.0.0-rc.1)
