### ISSUE TITLE
[Bug] Not receiving invalidation messages on RedisPool

### ISSUE THREAD

**Issue by sebastianhopkins-lh** [aembke/fred.rs#146]
Redis version - 7.0.5
Platform - mac
Using Docker and/or Kubernetes - no
Deployment type - centralized (pool)
fred.rs: 6.3.0

Invalidation messages are received with RedisClient but not with RedisPool. 

The following code works:

```rs
    // redis_config - server: centralised(localhost), version: resp3, all else default

    let basic = RedisClient::new(redis_config.clone(), None, None);
    let _ = basic.connect();
    basic.wait_for_connect().await?;

    basic
        .start_tracking(
            vec!["data"], // PREFIX
            true,         // BCAST
            false,        // OPTIN  (not compatible with BCAST)
            false,        // OPTOUT (not compatible with BCAST)
            false,        // NOLOOP (doesn't matter, we never modify keys)
        )
        .await?;

    {
        let mut invalidations = basic.on_invalidation();
        tokio::spawn(async move {
            while let Ok(invalidation) = invalidations.recv().await {
                println!("invalidation event");
            }
        });
    }
```

This prints "invalidation event" when you change a key starting with "data".

However, replace the first line to use RedisPool and it no longer prints anything.

```rs
    let basic = RedisPool::new(redis_config.clone(), None, None, 5)?;
```

**Logs**
I didn't get any log output 🤔

**Comment by aembke** [comment]
@sebastianhopkins-lh this should also be addressed in 7.x. The interface in 6.x is especially misleading here - when you call `start_tracking` or `on_invalidation` on the pool you're actually only calling it on one of the underlying clients. The new interface makes this explicit by requiring the caller to use `clients`, etc. You could also apply that to your v6 code, but the v7 interface should be easier.
