### ISSUE TITLE
[Bug] After one slot master node shutdown and recovery, the redis pool doesn't recovery

### ISSUE THREAD

**Issue by daji777** [aembke/fred.rs#155]
Platform - linux|mac|windows
Using Docker and/or Kubernetes - no
Deployment type - cluster

**Describe the bug**

**To Reproduce**
1. first I create this redis cluster:
`shard 1
10.100.42.166:7000(master)
10.100.42.166:7004(slave)
shard 2
10.100.42.166:7002(master and stop)
shard 3
10.100.42.166:7001(master)
10.100.42.166:7005(slave)`

2. my use this fred cfg :
`let reconnect = ReconnectPolicy::Constant {
        attempts: 3,
        max_attempts: 3,
        delay: 1000,
        jitter: 100,
    };
    let redis_pool = RedisPool::new(config, Some(PerformanceConfig::default()),
                                    Some(reconnect),size)?;`

3. After I shutdown 10.100.42.166:7002 only one master node in this shard, I got errors from fred, I think it's expected
`[INFO] [2023.06.19 11:44:46.069] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(70)] - librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/1001: Timed out OffsetCommitRequest in flight (after 60645ms, timeout #0)
[INFO] [2023.06.19 11:44:46.069] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(70)] - librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/1001: Timed out OffsetCommitRequest in flight (after 60645ms, timeout #1)
[INFO] [2023.06.19 11:44:46.069] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(70)] - librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/1001: Timed out OffsetCommitRequest in flight (after 60645ms, timeout #2)
[INFO] [2023.06.19 11:44:46.069] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(70)] - librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/1001: Timed out OffsetCommitRequest in flight (after 60645ms, timeout #3)
[INFO] [2023.06.19 11:44:46.069] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(70)] - librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/1001: Timed out OffsetCommitRequest in flight (after 60645ms, timeout #4)
[WARN] [2023.06.19 11:44:46.078] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(67)] - librdkafka: REQTMOUT [thrd:GroupCoordinator]: GroupCoordinator/1001: Timed out 11660 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
[ERROR] [2023.06.19 11:44:46.079] [127.0.0.1] [librdkafka] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(64)] - librdkafka: FAIL [thrd:GroupCoordinator]: GroupCoordinator: 10.100.41.246:9092: 11660 request(s) timed out: disconnect (after 60738ms in state UP)
[ERROR] [2023.06.19 11:44:46.446] [192.168.1.56] [rdkafka::client] [/.cargo/bin/bin/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.28.0/src/client.rs(106)] - librdkafka: Global error: OperationTimedOut (Local: Timed out): GroupCoordinator: 10.100.41.246:9092: 11660 request(s) timed out: disconnect (after 60738ms in state UP)`

4. but after I resume 10.100.42.166:7002, this cluster is still not work unless I restart my project.

How can I fix this issue without restart projects? 

**Logs**
(Set `RUST_LOG=fred=trace` and run with `--features debug-ids`)

**Additional context**

**Comment by aembke** [comment]
Hi @daji777, it looks like the error logs you provided there are from a kafka client. Do you happen to have the logs from the `fred` client? Also, could you include the version of fred that you're using?

**Comment by aembke** [comment]
Closing for now, but feel free to re-open if needed.
