### ISSUE TITLE
[Bug] 6.3.0 resp2: when use hmget with vec len = 1, will cause error   T::from_owned_bytes(bytes.to_vec()).ok_or(RedisError::new_parse("Cannot convert from bytes"))

### ISSUE THREAD

**Issue by xxaier** [aembke/fred.rs#158]
use resp2

when use hmget with vec len = 1, will cause error   

for example :

let vli: Vec<Option<Vec<u8>>> = KV.hmget("liMeta", vec![&[1, 2, 3][..]]).await?;
will cause 

T::from_owned_bytes(bytes.to_vec()).ok_or(RedisError::new_parse("Cannot convert from bytes"))

I use resp2 with [kvrocks](https://github.com/apache/kvrocks)
 
<img width="1902" alt="image" src="https://github.com/aembke/fred.rs/assets/130831741/957b266f-00cb-423a-9d8d-c4dbda97bb49">
I use redis cli, hmget return is array not bytes 

<img width="614" alt="image" src="https://github.com/aembke/fred.rs/assets/130831741/57b28d27-d00d-45c5-8afc-c868bf491390">

**Comment by aembke** [comment]
This should also be fixed in 7.x (starting at https://crates.io/crates/fred/7.0.0-rc.1). Unfortunately the fix was pretty invasive and required a major version bump. I'll leave this open until 7.0.0 is released though.

**Comment by aembke** [comment]
This should be fixed in [7.0.0](https://crates.io/crates/fred/7.0.0). Please let me know if you still see any issues here though.
