### ISSUE TITLE
[Bug] use pipeline & hmget (only get one) with resp2 not return Vec<Vec<Vec<u8>>>

### ISSUE THREAD

**Issue by xxaier** [aembke/fred.rs#165]
as title

**Comment by aembke** [comment]
This should be fixed in 7.x (starting at https://crates.io/crates/fred/7.0.0-rc.1). Unfortunately the fix was pretty invasive and required a major version bump. I'll leave this open until 7.0.0 is released though.

**Comment by aembke** [comment]
This should be fixed in [7.0.0](https://crates.io/crates/fred/7.0.0). Please let me know if you still see any issues here though.
