### ISSUE TITLE
compilation error - the trait bound `tokio::net::TcpStream: AsFd` is not satisfied

### ISSUE THREAD

**Issue by duan-jason** [aembke/fred.rs#174]
Redis version - Redis 7.0.8 (00000000/0) 64 bit
Platform -mac
Using Docker and/or Kubernetes -no
Deployment type - centralized

**Describe the bug**
getting below compilation error when using fred = "7.0.0", what could be wrong?

cargo build
    Blocking waiting for file lock on build directory
   Compiling fred v7.0.0
error[E0277]: the trait bound `tokio::net::TcpStream: AsFd` is not satisfied
   --> /Users/duan/.cargo/registry/src/github.com-1ecc6299db9ec823/fred-7.0.0/src/protocol/connection.rs:100:21
    |
100 |       SockRef::from(&socket).set_tcp_keepalive(keepalive)?;
    |       ------------- ^^^^^^^ the trait `AsFd` is not implemented for `tokio::net::TcpStream`
    |       |
    |       required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsFd`:
              &T
              &mut T
              Arc<T>
              BorrowedFd<'_>
              Box<T>
              OwnedFd
              Socket
              StderrLock<'a>
            and 19 others
    = note: required for `SockRef<'_>` to implement `From<&tokio::net::TcpStream>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `fred` due to previous error

**Logs**
see above

**Additional context**
i was able to compile the project if using fred = "6.3.2"

**Comment by aembke** [comment]
Hi @duan-jason, a few follow up questions:

* Which feature flags are you using for fred?
* Which version of tokio are you using? 
* Does your application use a specific `socket2` version?

**Comment by aembke** [comment]
Closing for now, but let me know if anybody is able to repro this.
