### ISSUE TITLE
read CLIENT ID failed should't cause connect failed

### ISSUE THREAD

**Issue by dupu222** [aembke/fred.rs#176]
I am using Redis 3.2.x, which does not support the  [CLIENT ID](https://redis.io/commands/client-id/) command. When I try to connect to a sentinel cluster, the fred client gives me an error.
![image](https://github.com/aembke/fred.rs/assets/13982466/87820e46-30d0-4014-a3a5-c770b50f6c9b)

Can we set RedisTransport.id to None when reading client id fails, so that we can avoid the above error?
https://github.com/aembke/fred.rs/blob/9bbb9221cbb1881b9ce2ff2e3b2754d6c0c68ab5/src/protocol/connection.rs#L621C19-L631
I can submit a PR to fix this issue, but I am not sure if RedisTransport.id being None will have any impact on the subsequent process.

**Comment by aembke** [comment]
Interesting, that makes sense but there are certainly some things that wont work if that field is none, such as the client unblocking logic. You're welcome to submit a PR and it'll likely fix your immediate issue, but I hadn't intended to support such old versions of Redis and I'm not sure what else might fail against that version.

**Comment by aembke** [comment]
Thanks @dupu222, your changes are included in https://github.com/aembke/fred.rs/releases/tag/v7.1.0
