### ISSUE TITLE
[Bug] username and password parsing from URL does not handle percent encoding

### ISSUE THREAD

**Issue by Geal** [aembke/fred.rs#186]
the `utils::parse_url_credentials` method gets the username and password from the URL using its direct methods:
https://github.com/aembke/fred.rs/blob/aa7fc0271b526f41ace297a6576b775bcd410c06/src/utils.rs#L735-L744

But those methods return the value as a percent encoded string: https://docs.rs/url/latest/url/struct.Url.html#method.username
> Return the username for this URL (typically the empty string) as a percent-encoded ASCII string.

So if we are parsing the config from the URL `redis://default:abc%2F123@localhost:6379`, then the password that will be sent to Redis would be `abc%2F123` instead of `abc/123`

**Comment by aembke** [comment]
This will be fixed in 7.1.0 (https://github.com/aembke/fred.rs/pull/187)

**Comment by aembke** [comment]
Thanks @Geal, this should be fixed in https://github.com/aembke/fred.rs/releases/tag/v7.1.0
