### ISSUE TITLE
[Bug] Scope for runtime error in HashesInterface

### ISSUE THREAD

**Issue by hrithikesh026** [aembke/fred.rs#191]
Redis version - 7.0.12
Platform - mac
Using Docker and/or Kubernetes - no
Deployment type - NA

**Describe the bug**
hset and hmset results in invalid redis command if emtpy Vec is passed as values.

**To Reproduce**
1. Create an instance of RedisPool .
2. use hset or hmset function with any key and empty Vec as value.

**Logs**
```
[src/main.rs:18] result = Err(
    Redis Error - kind: Unknown, details: ERR wrong number of arguments for 'hmset' command,
)
```

**Additional context**

**Comment by aembke** [comment]
Closing after the discussion in the linked issue.
