### ISSUE TITLE
[Bug] Incorrect cluster failover behavior

### ISSUE THREAD

**Issue by neogenie** [aembke/fred.rs#194]
Redis version - 6.2.7
Platform - linux
Using Docker and/or Kubernetes - no
Deployment type - cluster

Incorrect cluster failover behavior

**To Reproduce**
1. Down master node
2. Await replica promotes to master and cluster sync
3. Up master node
4. Apply `CLUSTER FAILOVER`
5. Library still never read key (Infinity incorrect `MOVED` handle)

**Comment by neogenie** [comment]
@aembke Pls, take a look

**Comment by aembke** [comment]
Thanks @neogenie, good find again. I just merged https://github.com/aembke/fred.rs/pull/195 and I think this is worth its own quick patch release in 7.1.1.
