### ISSUE TITLE
Can `CLIENT ID` command on startup be skipped?

### ISSUE THREAD

**Issue by rukai** [aembke/fred.rs#198]
on startup fred will send a CLIENT ID command to the server.
I am wondering if that is a hard requirement of the way fred is implemented or if its just a nice to have and we could expose a config to the user allowing it to be disabled?

**Comment by aembke** [comment]
Hey @rukai, it's not a hard requirement for the client to function at all, but some things may not work. In [7.1.0](https://github.com/aembke/fred.rs/releases/tag/v7.1.0) it was made optional (via https://github.com/aembke/fred.rs/issues/176), but I haven't fully tested the implications of that. 

If I had to guess it likely only impacts the connection blocking interface (`Blocking::Error` or `Blocking::interrupt`), but I'm not entirely sure.

**Comment by rukai** [comment]
ah, funnily enough, I actually want the opposite of that PR.
My use case is that I have a redis proxy, and if the proxy is misconfigured then it will send an error response upon receiving its first request and then terminate the connection.
So if fred sends a message on connection init and then discards the result, the connection will be terminated with no error given to the user.

So I either want to:
* wait_for_connect should return Err containing error response of `CLIENT ID` when it fails.
* skip running `CLIENT ID` all together

**Comment by aembke** [comment]
Oh I see what you mean. If the first command was `AUTH` or `HELLO` would you see the error then?

I could also change the init logic to send `PING` first if no creds are provided. In that case the first command would always be `PING`, `AUTH`, or `HELLO`, and the client wouldn't ignore the result of any of those.

**Comment by rukai** [comment]
That would fix the issue yeah, but I imagine most people would prefer to avoid sending further unnecessary commands as that would delay start up of the application.

**Comment by rukai** [comment]
Oh wait, but as you said it already sends AUTH when using authentication right?
Then it would just be bringing it to the same level as an authenticated session which seems fine.

**Comment by aembke** [comment]
Sounds good. I added this in my working branch so it'll be included in 8.0.0.

**Comment by aembke** [comment]
Added in 8.0.0 (https://github.com/aembke/fred.rs/pull/199)
