### ISSUE TITLE
How to use streams?

### ISSUE THREAD

**Issue by 8192K** [aembke/fred.rs#200]
Hi Alec,
How can I use (XADD, XREAD, XREADGROUP) from Redis streams with Fred?
What I am especially looking for is some easy way to subscribe to stream messages coming in.
Is there a comparison of speed, memory usage and features with the redis-rs crate somewhere?

Thanks a lot.

**Comment by aembke** [comment]
Hi @8192K, 

Here's a few options showing stream examples:
* The [integration tests](https://github.com/aembke/fred.rs/blob/main/tests/integration/streams/mod.rs) cover most of the interfaces but use somewhat contrived examples.
* I added a [streams example](https://github.com/aembke/fred.rs/blob/feat/unix-sockets/examples/streams.rs) in my working branch. It'll be included in the main examples folder with the next release. I'm not expecting any of the streams interface to change between releases in the future. 

In terms of performance or a more detailed technical breakdown - sort of. I've been meaning to write a design document for a while but only recently started including this in the repo. Here's a few links you may find useful, but some of these are tied to the next release (planned for this month). 

* [A benchmarking tool will be included with the next release.](https://github.com/aembke/fred.rs/tree/feat/unix-sockets/bin/benchmark) You might find the README and examples section helpful.
* [I'm in the process of working on a more detailed design doc.](https://github.com/aembke/fred.rs/blob/feat/unix-sockets/docs/README.md) It's still a work in progress but aims to provide a quick overview for anybody that wants to evaluate this in more detail. 
* The [redis-protocol](https://github.com/aembke/redis-protocol.rs) crate implements a zero-copy RESP2 and RESP3 parser so memory usage is generally minimal. Ultimately this really depends more on your use case or app code, however.

**Comment by aembke** [comment]
Closing for now, but feel free to reopen if you have other questions.
