### ISSUE TITLE
[Bug] Error calling QUIT on backchannel

### ISSUE THREAD

**Issue by dracarys18** [aembke/fred.rs#203]
Redis version - 7.0.7
Platform - linux
Using Docker and/or Kubernetes - yes
Deployment type - cluster

**Describe the bug**
```fred-MKFplnWfjb: Error calling QUIT on backchannel: Redis Error - kind: IO, details: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }``` 

Getting this log popped up once every hour 

**Logs**
fred-MKFplnWfjb: Error calling QUIT on backchannel: Redis Error - kind: IO, details: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
(Set `RUST_LOG=fred=trace` and run with `--features debug-ids`)

**Comment by dracarys18** [comment]
Thanks for the response @aembke . Can I know why is this happening? That too intermittently every hour?

**Comment by aembke** [comment]
The client sometimes maintains an extra backchannel connection that it uses to inspect or modify the other connections, but it only checks the health of this on the rare occasions when it needs to use it. The error here means that this connection was already closed when trying to call QUIT, so it should be harmless. 

Regarding why it happens every hour - I'm not sure, it could be many things. If I had to guess either something downstream closed the connection or perhaps the cluster synchronization process is set up to happen periodically. There's nothing in the client that runs on an hourly interval though, so it's likely something specific to your app or environment.

**Comment by aembke** [comment]
Fixed in 8.0.0 (https://github.com/aembke/fred.rs/pull/199)
