### ISSUE TITLE
SORT or SORT_RO missing

### ISSUE THREAD

**Issue by driusan** [aembke/fred.rs#216]
Is there any way to execute a [SORT](https://redis.io/commands/sort/) (or [SORT_RO](https://redis.io/commands/sort_ro/)) redis command using this client? It doesn't seem to be included in any of the fred::interfaces::* interfaces that I can find but I may be looking at the wrong place.

**Comment by aembke** [comment]
Good callout, looks like those functions are missing. I'll add them in the next version, but in the meantime you can use the [custom](https://docs.rs/fred/latest/fred/interfaces/trait.ClientLike.html#method.custom) function to send pretty much anything to the server.

```rust
client.lpush("foo", vec![1,2,3,4]).await?;
let result: Vec<i64> = client.custom(cmd!("SORT"), vec!["foo", "LIMIT", "0", "3", "DESC"]).await?;
```

**Comment by aembke** [comment]
Will be added in https://github.com/aembke/fred.rs/pull/234

**Comment by aembke** [comment]
Added in https://github.com/aembke/fred.rs/releases/tag/v9.0.0
