### ISSUE TITLE
[Bug]When a Redis cluster's primary machine fails and a standby Redis node takes over, it takes too long for Fred to rediscover and connect to the new primary.

### ISSUE THREAD

**Issue by gupta-mukul** [aembke/fred.rs#232]
Redis version - 7.0.4
Platform - linux
Using Docker and/or Kubernetes - yes (kubernetes)
Deployment type - cluster

**Describe the bug**
This problem becomes more apparent when operating in 1+1 mode (1 Primary and 1 Secondary). We have a Kubernetes (k8s) deployment where the primary and secondary run on different machines. A Cluster IP service sits in front of Redis Pods. This service's hostname is configured as the initial address when initializing Fred.
![image](https://github.com/aembke/fred.rs/assets/52314959/f6d46108-c05d-48ed-a217-f6032681360d)

When the primary machine goes down, it results in a stale connection from Fred.
![image](https://github.com/aembke/fred.rs/assets/52314959/d9bf8429-7803-493a-bfbc-e222f2d6e9eb)

Once Fred discovers an unresponsive connection, it initiates cluster rediscovery (cluster_slots_backchannel). It first tries sending cluster slots through the existing backchannel connection. Since the only connection available is the unresponsive one, it fails.

It then tries sending QUIT on the same channel, which fails again. It then attempts to select an address from the pool {service IP, old master IP}. Now, there is a 50% chance of either IP getting selected. If the old master IP gets selected, the connection attempt will fail. If the service IP gets selected, Fred will connect to the new primary and connectivity will be restored.
While this recovery time may not be bad for certain use cases, it may not work for other applications.

**Issues with cluster rediscovery**
1. While trying existing connections, unresponsive connections should be excluded.
2. QUIT should not be attempted on a connection for which the cluster slot command was not received/which is unresponsive.
3. While attempting a new connection, the connection to IP with an unresponsive connection may or may not work. If the only connection is bad, reconnecting will work. If the node is down, it will not work. Also, with multiple IPs available, the probability of selecting the unresponsive IP is 1/n. In the specific scenario described above, it becomes more apparent as the probability of selecting the old master IP is 50%. For a Kubernetes setup, where the initial server configuration is a Kubernetes service, it is always advantageous to attempt reconnection through it as it will always connect to a ready Redis pod.

**Proposal**
1. Avoid trying unresponsive connections for rediscovery.
2. Avoid sending QUIT when the cluster slots response is not received during rediscovery.
3. Provide an option to use the initial server configuration for attempting a new connection during discovery (and skip using the old cache).
OR
Provide an option to go directly for a new connection attempt using the initial server configuration for rediscovery.

**Logs**
```
{"msg":"fred-bF75M92Xma: Synchronizing cluster state.","level":"DEBG","ts":"2024-03-26T07:25:00.399865256Z"}
{"msg":"fred-bF75M92Xma: Error calling QUIT on backchannel: Redis Error - kind: IO, details: Os { code: 32, kind: BrokenPipe, message: \"Broken pipe\" }","level":"DEBG","ts":"2024-03-26T07:25:00.400075899Z"}
{"msg":"fred-bF75M92Xma: Failed reconnecting with error: Redis Error - kind: Protocol, details: Invalid or missing CLUSTER SLOTS response.","level":"DEBG","ts":"2024-03-26T07:25:00.400146852Z"}
{"msg":"fred-bF75M92Xma: Sleeping for 60 ms.","level":"DEBG","ts":"2024-03-26T07:25:00.400250773Z"}
{"msg":"fred-bF75M92Xma: Sleeping for 60 ms","level":"DEBG","ts":"2024-03-26T07:25:00.40028611Z"}
{"msg":"fred-bF75M92Xma: Synchronizing cluster state.","level":"DEBG","ts":"2024-03-26T07:25:00.461659674Z"}
{"msg":"fred-bF75M92Xma: Attempting clustered connections to any of {Server { host: \"10.244.142.136\", port: 6379 }, Server { host: \"redis-cluster.core.svc.cluster.local\", port: 6379 }}","level":"DEBG","ts":"2024-03-26T07:25:00.461763747Z"}
{"msg":"fred-bF75M92Xma: Creating TCP connection to 10.244.142.136 at 10.244.142.136:6379","level":"DEBG","ts":"2024-03-26T07:25:00.462029167Z"}
{"msg":"fred-bF75M92Xma: Error connecting to 10.244.142.136:6379: Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" }","level":"DEBG","ts":"2024-03-26T07:25:00.462195642Z"}
{"msg":"fred-bF75M92Xma: Creating TCP connection to redis-cluster.core.svc.cluster.local at 10.106.187.118:6379","level":"DEBG","ts":"2024-03-26T07:25:00.463117792Z"}
{"msg":"fred-bF75M92Xma: Switching to RESP3 protocol with HELLO...","level":"DEBG","ts":"2024-03-26T07:25:00.463667908Z"}
{"msg":"fred-bF75M92Xma: Read client ID: Ok(Number { data: 1098, attributes: None })","level":"DEBG","ts":"2024-03-26T07:25:00.464654551Z"}
{"msg":"fred-bF75M92Xma: Read server version Some(Version { major: 7, minor: 0, patch: 12 })","level":"DEBG","ts":"2024-03-26T07:25:00.465136896Z"}


{"msg":"fred-bF75M92Xma: Connected to redis-cluster.core.svc.cluster.local:6379 (2/2)","level":"DEBG","ts":"2024-03-26T07:25:00.465697156Z"}
{"msg":"fred-bF75M92Xma: Rebuilding cluster state from host: redis-cluster.core.svc.cluster.local","level":"DEBG","ts":"2024-03-26T07:25:00.466256714Z"}
{"msg":"fred-bF75M92Xma: Cluster routing state: {Server { host: \"10.244.46.24\", port: 6379 }: ([(0, 16383)], {})}","level":"DEBG","ts":"2024-03-26T07:25:00.466330176Z"}
{"msg":"fred-bF75M92Xma: Changing cluster connections: ClusterChange { add: [Server { host: \"10.244.46.24\", port: 6379 }], remove: [] }","level":"DEBG","ts":"2024-03-26T07:25:00.466380444Z"}
{"msg":"fred-bF75M92Xma: Connecting to cluster node 10.244.46.24:6379","level":"DEBG","ts":"2024-03-26T07:25:00.466436696Z"}
{"msg":"fred-bF75M92Xma: Creating TCP connection to 10.244.46.24 at 10.244.46.24:6379","level":"DEBG","ts":"2024-03-26T07:25:00.466562892Z"}
{"msg":"fred-bF75M92Xma: Switching to RESP3 protocol with HELLO...","level":"DEBG","ts":"2024-03-26T07:25:00.467058123Z"}
{"msg":"fred-bF75M92Xma: Read client ID: Ok(Number { data: 1099, attributes: None })","level":"DEBG","ts":"2024-03-26T07:25:00.467859552Z"}
{"msg":"fred-bF75M92Xma: Read server version Some(Version { major: 7, minor: 0, patch: 12 })","level":"DEBG","ts":"2024-03-26T07:25:00.468256001Z"}
{"msg":"fred-bF75M92Xma: Finish synchronizing cluster connections.","level":"DEBG","ts":"2024-03-26T07:25:00.468762254Z"}
{"msg":"fred-bF75M92Xma: No `on_connect` listeners.","level":"DEBG","ts":"2024-03-26T07:25:00.468822298Z"}
```

**Additional context**
My understanding of how it works and what backchannel means may be incorrect. Please correct my understanding if the description does not make sense. I tested by directly attempting to connect to the initial configured k8s service (by modifying cluster_slots_backchannel).

**Comment by aembke** [comment]
Hey @gupta-mukul, thanks for the in-depth writeup here. 

I included your suggestions in https://github.com/aembke/fred.rs/pull/234 so feel free to give them a try and let me know if you have any thoughts. I'm hoping to merge this sometime later in the week but might change things if folks have feedback.

**Comment by aembke** [comment]
Added in [9.0.0](https://github.com/aembke/fred.rs/releases/tag/v9.0.0) as the `ClusterDiscoveryPolicy::ConfigEndpoint` variant. This is the default too, so you shouldn't have to change anything. In my tests against some large clusters this dramatically reduced the end to end failover delays. Thanks again.

**Comment by gupta-mukul** [comment]
@aembke Thanks for the fast resolution. I apologize for not being able to retest and share the result in time. I will definitely do that this week.
