### ISSUE TITLE
[Feature] Exponential backoff to reconnect if Redis was not running initially

### ISSUE THREAD

**Issue by vrrashkov** [aembke/fred.rs#259]
I am not really sure if I am missing something, but the configuration for the connection settings, currently works only if previously we have connected to Redis instance, Redis goes down and then fred-rs tries to reconnect to the instance. But if the case is where Redis is down before the first initial connection with `cache_client.init().await?` it throws an error "Connection refused" and doesn't try to reconnect. Can the exponential backoff on reconnect also be used for the initial connection?

**Comment by aembke** [comment]
Hi @vrrashkov, I'll improve the docs on this, but try setting [fail_fast](https://docs.rs/fred/latest/fred/types/struct.RedisConfig.html#structfield.fail_fast) to false when setting up the `RedisConfig`.

**Comment by vrrashkov** [comment]
Thank you, I have missed that one!
