### ISSUE TITLE
[Feature] Enabling the Redisearch interface through Cargo

### ISSUE THREAD

**Issue by diviyank** [aembke/fred.rs#263]
**Describe the solution you'd like**
Hello, thank you for your amazing package! I started using it but I'm having trouble enabling the option i-redisearch through cargo: 

<img width="640" alt="image" src="https://github.com/aembke/fred.rs/assets/20682356/4ebcd9bc-f2a4-4694-86ab-aac0cb465198">

I¨m using v9.0.3.

Is there something I'm doing wrong? 

Thank you & have a nice day

**Comment by aembke** [comment]
Hi @diviyank, at the moment the `i-redisearch` feature is only available on github in the main branch. I'm planning on hopefully releasing 9.1.0 later this week though.

**Comment by diviyank** [comment]
Great thank you !
