### ISSUE TITLE
[Feature] Replace `trust-dns-resolver` with `hickory-resolver`

### ISSUE THREAD

**Issue by aumetra** [aembke/fred.rs#265]
**Describe the solution you'd like**

It's not quite a bug but also not quite a feature but I just went ahead and made it a feature request. Not sure.

`trust-dns` rebranded to `hickory-dns` and now publishes under this new name. `fred` should change its dependency to `hickory-resolver` accordingly.

**Comment by aumetra** [comment]
Looking at the code, is the `trust-dns` dependency even actively used?

**Comment by aembke** [comment]
Thanks @aumetra, added in https://github.com/aembke/fred.rs/releases/tag/v9.1.0
