### ISSUE TITLE
[Feature] Options for `EXPIRE` commands

### ISSUE THREAD

**Issue by stepantubanov** [aembke/fred.rs#266]
[EXPIRE](https://redis.io/docs/latest/commands/expire/) command has options `NX`, `XX`, `GT`, `LT` which aren't supported by fred at the moment. It'd be nice to add them. They were added in Redis 7.0.

Same options exist for `PEXPIRE`, `EXPIREAT`, `PEXPIREAT`.

EDIT: Seems like `pexpire` command isn't implemented, it'd be nice to add it too.

**Comment by aembke** [comment]
Added in v10.0.0 (https://github.com/aembke/fred.rs/pull/314)
