### ISSUE TITLE
[Bug] Conversion from `u64::MAX` into `RedisValue` fails

### ISSUE THREAD

**Issue by stepantubanov** [aembke/fred.rs#271]
Fred version - 9.0.3

**Describe the bug**

Attempt to set a key to `u64::MAX` fails:
```rust
conn.set("key", u64::MAX, None, None, false).await?;
// returns error `Redis Error - kind: Unknown, details: Unsigned integer too large`
```

Can be worked around by explicitly converting to string. But getting `u64::MAX` integer works fine:
```rust
// Using `to_string` works for setting.
conn.set("key", u64::MAX.to_string(), None, None, false).await?;

let v: u64 = conn.get("key").await?;
assert_eq!(v, u64::MAX); // passes
```

**Comment by aembke** [comment]
Yeah, I'm not sure there's a great solution here. The representation for numbers in redis and on the wire is a signed 64-bit integer, so I intentionally made anything >2^63 fail the automatic type conversion to avoid this kind of thing:

```
redis-main:6379> set foo 18446744073709551616
OK
redis-main:6379> decr foo
(error) ERR value is not an integer or out of range
```

If you're only operating on the value as a number in app code then I can see why this would be annoying, but the alternative approach of hiding a `to_string`, and thereby changing the allowed operations on the server, seemed worse in my opinion. The intention here was to make it explicit to the user that the underlying value must be stored and operated on as a string on the server.

**Comment by aembke** [comment]
Closing for now, but let me know you want to reopen or propose any changes for this.
