### ISSUE TITLE
[Bug] Syntax error with tower-sessions-redis-store on insert 

### ISSUE THREAD

**Issue by J-Schoepplenberg** [aembke/fred.rs#272]
Fred version - 9.0.3
Redis version - 3.0.504 (64 bit, Microsoft native Redis port: [Link](https://github.com/ServiceStack/redis-windows/blob/master/README.md#current-version-30503-june-28-2016))
Platform - Windows 10
Deployment type - centralized

Consider this simple example:

```Rust
let redis_pool = RedisPool::new(RedisConfig::default(), None, None, None, 6)?;
let redis_connection = redis_pool.connect();
redis_pool.wait_for_connect().await?;
let session_store = RedisStore::new(redis_pool);
let session_layer = SessionManagerLayer::new(session_store)
        .with_secure(false)
        .with_expiry(Expiry::OnInactivity(Duration::minutes(30)));
let app = Router::new()
        .route("/", get(handler))
        .layer(session_layer);
let socket_addr = SocketAddr::from(([127, 0, 0, 1], 3000));
let listener = tokio::net::TcpListener::bind(socket_addr)
        .await
        .unwrap();
axum::serve(listener, app.into_make_service()).await.unwrap();
redis_connection.await??;
```

where

```Rust
const COUNTER_KEY: &str = "counter";

async fn handler(session: Session) -> impl IntoResponse {
    let counter: Counter = session.get(COUNTER_KEY).await.unwrap().unwrap_or_default();
    session.insert(COUNTER_KEY, counter.0 + 1).await.unwrap(); // Error seems to be caused here.
    format!("Current count: {}", counter.0)
}
```

This is using:

```Cargo.toml
axum = "0.7.5"
tower-sessions = "0.12.2"
tower-sessions-core = "0.12.2"
tower-sessions-redis-store = "0.13.0"
```

`tower-sessions` is using fred, see: [issue](https://github.com/maxcountryman/tower-sessions-stores/issues/40#issuecomment-2254143065).

**Logs**
This will run on the error:

```bash
2024-07-27T12:43:09.628647Z ERROR call:save: tower_sessions_core::session: error=Unknown Error: ERR syntax error
2024-07-27T12:43:09.629107Z ERROR call: tower_sessions::service: failed to save session err=Unknown Error: ERR syntax error
```

**Comment by aembke** [comment]
Hi @J-Schoepplenberg, it looks like the version of Redis you're using is based on a 2016 release of Redis, likely before the NX argument was supported, and the tower sessions library depends on this to prevent session ID collisions. I would recommend updating to a more recent Redis version that supports the NX argument on SET commands.

**Comment by J-Schoepplenberg** [comment]
Hey @aembke. Yeah, I already did that and all works as expected. Just wanted to note that there is this issue if using the native Microsoft port of Redis. They do not have a newer version available.
