### ISSUE TITLE
[Feature] RedisConfig::from_url should handle `redis+unix` scheme

### ISSUE THREAD

**Issue by LordMZTE** [aembke/fred.rs#273]
**Describe the solution you'd like**
The function `RedisConfig::from_url` does not seem to handle URLs specifying UNIX socket connections. As such, a URL with the `redis+unix` scheme such as `redis+unix:///run/redis/redis.sock` will fail to be parsed. We should handle this scheme accordingly.

**Comment by aembke** [comment]
Thanks @LordMZTE, added in https://github.com/aembke/fred.rs/releases/tag/v9.1.0

**Comment by LordMZTE** [comment]
Thank you!
