### ISSUE TITLE
[Feature] async operations inside on_message

### ISSUE THREAD

**Issue by dracarys18** [aembke/fred.rs#276]
**Describe the solution you'd like**
The current implementation of `on_message` function in pubsub does not allow us to use async functions inside the function. The changes for this would include changing the constraints on `on_message` function to 
```rust
  fn on_message<F>(&self, func: F) -> JoinHandle<RedisResult<()>>
  where
    F: Fn(Message) -> impl Future<Output = RedisResult<()>> + Send + 'static,
```

**Additional context**
NA

**Comment by aembke** [comment]
Added in 10.0.0 (https://github.com/aembke/fred.rs/pull/314)
