### ISSUE TITLE
[Feature] Add credential provider callback

### ISSUE THREAD

**Issue by nakedible-p** [aembke/fred.rs#284]
**Describe the solution you'd like**
When using AWS ElastiCache for Redis or AWS MemoryDB, there's the possibility to use IAM authentication. How this works is that the authentication token is passed as a password to the Redis database. However, the authentication token is only valid for 15 minutes. While this works for initial connection, it means that when the client reconnects, the token will no longer be valid.

Currently there doesn't seem to be a way to change the "password" for a RedisClient or RedisPool after it has been created. And even if there were, if there's no way to know when reconnections happen, the token would have to be kept up-to-date all the time.

A better approach would be to allow configuring a credential provider hook, an async function that returns username+password, that would be called every time authentication credentials are needed, namely here: https://github.com/aembke/fred.rs/blob/main/src/protocol/connection.rs#L685-L686

Note that I am not proposing to integrate AWS SigV4 authentication inside this client (which would tie this to AWS), but only provide a way to generate the token on-demand.

*I am probably able to contribute a solution to this as a pull request, if there is consensus that this is a worthwhile feature to add.*

**Additional context**
An additional issue is that AWS MemoryDB will forcibly disconnect a client after 12 hours, unless that client resends an `AUTH` command. This would be solved by adding a maximum connection lifetime option where the client would automatically reconnect connections after some time - or even more specifically a reauthentication timeout where the client would resend `AUTH` after that time.

However, this is a probably a separate issue to solve, and can also be solved somewhat more easily in application code.

**Comment by aembke** [comment]
This will be added in 9.2.0 (https://github.com/aembke/fred.rs/pull/288) 

Regarding the 12 hour disconnect - does MemoryDB respond with a NOAUTH error after 12 hours? The [reconnect_on_auth_error](https://docs.rs/fred/latest/fred/types/struct.ConnectionConfig.html#structfield.reconnect_on_auth_error) field may have the same effect as what you're looking for. IIRC that was added to deal with a similar issue with ElastiCache.

**Comment by nakedible-p** [comment]
No, MemoryDB will forcibly close the connection after 12 hours. This means that in the unlucky case a command has just been sent when the closing happens, it will get lost (unless it is idempotent and can safely be retried).

**Comment by aembke** [comment]
This should be working in https://github.com/aembke/fred.rs/releases/tag/v9.2.0, but let me know if you still have any issues.
