### ISSUE TITLE
[Feature] Support the SETNX command

### ISSUE THREAD

**Issue by AverageADF** [aembke/fred.rs#294]
**Describe the solution you'd like**
The [`SETNX`](https://redis.io/docs/latest/commands/setnx/) command should be added to the [`KeysInterface`](https://docs.rs/fred/latest/fred/interfaces/trait.KeysInterface.html) trait.

**Additional context**
I known this command is regarded as deprecated and that we should use `SET` with the `NX` option but I would like to prevent clients from overriding existing keys with Redis [ACL](https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/) which is only possible with the `SETNX` command.

**Comment by aembke** [comment]
Thanks @AverageADF, this is added in 9.3.0
