### ISSUE TITLE
[Bug] `WITHSCORE` argument not available in `zrank` and `zrevrank`

### ISSUE THREAD

**Issue by bismitpanda** [aembke/fred.rs#311]
Fred version - 9.4.0

**Describe the bug**

The commands [`zrank`](https://redis.io/docs/latest/commands/zrank/) and [`zrevrank`](https://redis.io/docs/latest/commands/zrevrank/) accept an optional `WITHSCORE` argument to return the score along with the rank. But fred does not seem to support this. The method signatures of the functions in the sorted sets interface are

```rs
fn zrank<R, K, V>(&self, key: K, member: V) -> impl Future<Output = RedisResult<R>> + Send {
  // ...
}
```

```rs
fn zrevrank<R, K, V>(&self, key: K, member: V) -> impl Future<Output = RedisResult<R>> + Send {
  // ...
}
```

Is there any reason not to support this? If it was a miss I am open to add this to  the crate.

**Comment by aembke** [comment]
Hey @bismitpanda, this'll be added in the next version (https://github.com/aembke/fred.rs/pull/314). Unfortunately it requires a breaking change to those function signatures.

**Comment by bismitpanda** [comment]
Ok sure, when is it expected to be merged?
