### ISSUE TITLE
How can I configure the server parameters?

### ISSUE THREAD

**Issue by juanki03** [aembke/fred.rs#39]
Hello! I need to create an instance of RedisClient with my own parameters. But I only see the default function. Where I can set up my host and port to RedisConfig?

Also, where i can set a new client name?

Thank you!

**Comment by aembke** [comment]
Hi @juanki03,

There's a few ways to do this, but I would recommend checking out the [basic starter examples](https://github.com/aembke/fred.rs/blob/main/examples/basic.rs) to see the full config options.

However, you don't need to use every field there. You can also do something like this:

```
  let config = RedisConfig {
    server: ServerConfig::new_centralized("127.0.0.1", 6379),
    .. Default::default
    },
  };
  // configure exponential backoff when reconnecting, starting at 100 ms, and doubling each time up to 30 sec.
  let policy = ReconnectPolicy::new_exponential(0, 100, 30_000, 2);
  let client = RedisClient::new(config);
```

**Comment by juanki03** [comment]
Thank you! Another question @aembke : 

How can I change the name of the client, which comes by default "fred-" ?

**Comment by oscartbeaumont** [comment]
@aembke is there a way to convert a Redis connection URL into a `RedisConfig` struct. This would be very useful when loading the Redis configuration from environment variables without having to define a heap of different variables.

**Comment by aembke** [comment]
@juanki03 you can use the `client_setname` function to do that. 

@oscartbeaumont there isn't at the moment, but that's a great idea. I'm going to add that to the PR for 5.0.0 so it'll be available shortly.

**Comment by oscartbeaumont** [comment]
Thanks!

**Comment by aembke** [comment]
Closing this for the time being, but feel free to re-open if you have any more questions.

@oscartbeaumont the URL parsing changes are in the main branch now, which I'm planning on releasing shortly as 5.0.0.
