### ISSUE TITLE
Disable CLIENT SETNAME on connect

### ISSUE THREAD

**Issue by zackangelo** [aembke/fred.rs#42]
Is there a way to disable the `CLIENT SETNAME` call during authentication? 

Proxies like [twemproxy](https://github.com/twitter/twemproxy) don't support it.

**Comment by aembke** [comment]
Oh interesting, I didn't know some proxies prevented that. I'll make a patch that can disable that this weekend, but currently I don't think there's a way to avoid it.

**Comment by zackangelo** [comment]
If you have a high-level idea around how you'd like it implemented, I'm also happy to raise a PR.

**Comment by aembke** [comment]
I added a feature flag `no-client-setname` in 5.1.0 for this. Let me know if that helps or if you still have any issues here.
