### ISSUE TITLE
[Bug] Type `ClusterRouting` is not `pub` thus `ClusterLike::cached_cluster_state()` can not be used

### ISSUE THREAD

**Issue by kika** [aembke/fred.rs#81]
**Describe the bug**

The following code does not compile:
```rust
use fred::{prelude::*, protocol::types::ClusterRouting};

#[tokio::main]
async fn main() -> Result<(), RedisError> {
    pretty_env_logger::init();

    let config = RedisConfig::from_url("redis-cluster://127.0.0.1:7000").expect("Creating config");
    let cluster_client = RedisClient::new(config, None, None);
    let _ = cluster_client.connect();
    let _ = cluster_client.wait_for_connect().await?;
    let cluster_state: Option<ClusterRouting> = cluster_client.cached_cluster_state();
    if let Some(state) = cluster_state  {
        println!("Cluster state: {:?}", state);
    }
    Ok(())
}
```
because `fred::protocol` is private.

it could be made compile by inferring the return type of `cached_cluster_state()` but that doesn't work in `struct`s.

Change this to `pub mod` and it works: https://github.com/aembke/fred.rs/blob/8c3131be37a6e3c729ba8f13482caf10305ebd5e/src/lib.rs#L74

**Comment by aembke** [comment]
Thanks for taking a closer look at all this stuff. I'll get an update out hopefully later today.

**Comment by kika** [comment]
I actually reported this one on the beta1 or beta2 PR, but I guess the comment went unnoticed :-)
