### ISSUE TITLE
[Feature-request] Improve `watch` interface for transactions (`multi`)

### ISSUE THREAD

**Issue by DDtKey** [aembke/fred.rs#90]
New interface for transactions in `6.0.0` is much better and allowed to relax my personal customization around it.
But there is one issue, sometimes it's needed to combine `watch` and `multi`.

But `watch` can't be called inside multi block, so I wonder if it possible to somehow combine them and prevent re-ordering of related `watch` and `multi`?  
Currently it's possible to watch in parallel, so order will be:
```
watch K1
watch K2
multi
set K1 1
exec

# watch K2 is also was unwatched
```

I mean `exec` of `multi` block automatically `unwatch` keys on redis side, so it's possible that within one `fred`-connection I will call `N` `watch` operations and then any `exec` will discard them together which is incorrect/unexpected behavior for this combination. 

For now I have to manually lock connection or create new one for such operations, it's a bit counterproductive. Instead I like to order their execution and combine them as atomic block.

I mean something like `connection.multi_with_watch(keys)` and it will be applied in this order:
```
... commands before ....

watch
multi .... exec 

... commands after ....
```

It could be tricky one, but I'd like to have similar interface to avoid collision between `multi/exec` and `watch`es related to another transaction

**Comment by aembke** [comment]
Yeah that all makes sense. How about a `watch_before` function on the `Transaction` struct that buffers the `WATCH` commands with the transaction commands?

**Comment by DDtKey** [comment]
It looks good to me, even better I think

**Comment by aembke** [comment]
Added in https://github.com/aembke/fred.rs/pull/92
